### ISSUE TITLE
SMASH THE LIKE!!!!!!

### ISSUE THREAD

**Issue by generictem** [JoseRivas1998/TCG-soundboard#2]
Sound Title:SMASH THE LIKE!!

Link to Sound:
#https://youtu.be/dlMrmwgFsC0 0:04  secs

NOTE: If sound is from YouTube video, please include the time in the YouTube link.

**Comment by JoseRivas1998** [comment]
This is fantastic, will be included in the next update!

**Comment by generictem** [comment]
thx bro
