### ISSUE TITLE
Jontron - Kid + Skateboard [The Skateboard Kid]

### ISSUE THREAD

**Issue by generictem** [JoseRivas1998/TCG-soundboard#5]
Sound Title:
Kid + Skateboard = skateboard kid

Link to Sound: #https://youtu.be/UJzk9E_ZuDU 0.21 seconds 

NOTE: If sound is from YouTube video, please include the time in the YouTube link.

**Comment by generictem** [comment]
forgot the time of the video lol

**Comment by JoseRivas1998** [comment]
This is too long

**Comment by generictem** [comment]
oh ok
